import "./globals.css";
import Navbar from "./components/layout/Navbar";

import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./components/common/Loading";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.3.1/css/all.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col px-[154px]">
        <Suspense fallback={<Loading />}>
          <Navbar />
        </Suspense>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
